alter table public.submissions
  add column availability text,
  add column location text,
  add column csn_before text,
  add column ged_hiset text,
  add column heard_about text,
  add column transportation text,
  add column level text,
  add column improve text,
  add column studied_before text,
  add column passed_subjects text,
  add column support_subject text,
  add column area text,
  add column prior_experience text,
  add column work_authorization text;
